services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/influxdb-data:/var/lib/influxdb2
      - ./influxdb/influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=telegraf
      - DOCKER_INFLUXDB_INIT_PASSWORD=geheim123456
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
    restart: always
    networks: 
      - iot

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 8002:3000
  #   volumes:
  #     - ./grafana/grafana-data:/var/lib/grafana
  #     - ./grafana/grafana-log:/var/log/grafana
  #   environment:
  #     - GF_SERVER_ROOT_URL=http://iotserver:8002
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   restart: always
  #   depends_on:
  #     - influxdb
  #   networks: 
  #     - iot

  broker:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    ports:
      - "1883:1883"
    networks: 
      - iot
    depends_on: 
      - influxdb
    restart: always

  telegraf:
    image: telegraf:1.24
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf-log:/var/log/telegraf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/host/var/run/utmp:ro
      - /:/rootfs:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_VAR=/host/var
    restart: always
    depends_on:
      - influxdb
      - broker
    networks: 
      - iot

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NVM_DIR=/root/.nvm
      - NODE_VERSION=18
    volumes:
      - .:/app
    depends_on:
      - dependencies

  dependencies:
    build:
      context: .
      dockerfile: Dockerfile.dependencies
    volumes:
      - .:/app

volumes:
  nodered:

networks:
  iot: